[package]
name = "min"
version = "0.1.0"
authors = ["Michael Gattozzi <mgattozzi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.13"
futures = "0.3"
tokio = { version="0.2", features=["full"] }
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = "0.2"
